"""Email unique

Revision ID: 0813d29187b3
Revises: 2bd20cafcb14
Create Date: 2023-08-15 06:11:52.578781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0813d29187b3'
down_revision = '2bd20cafcb14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_contact_uc', 'contacts', type_='unique')
    op.create_unique_constraint('_contact_uc', 'contacts', ['name', 'lastname'])
    op.create_unique_constraint(None, 'contacts', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_constraint('_contact_uc', 'contacts', type_='unique')
    op.create_unique_constraint('_contact_uc', 'contacts', ['name', 'lastname', 'email'])
    # ### end Alembic commands ###
